const express = require('express');

const router = express.Router();

router.use('/public', require('./public'));
router.use('/auth', require('./auth'));
router.use('/super-admin', require('./superAdmin'));
router.use('/college-admin', require('./collegeAdmin'));
router.use('/attendance', require('./attendance'));
router.use('/exams', require('./exam'));
router.use('/assignments', require('./assignment'));
router.use('/timetable', require('./timetable'));
router.use('/fees', require('./fee'));
router.use('/ai', require('./ai'));
router.use('/leave', require('./leave'));
router.use('/hr', require('./leave'));
router.use('/logistics', require('./logistics'));
router.use('/transport', require('./transport'));
router.use('/hostel', require('./hostel'));
router.use('/hostels', require('./hostel'));
router.use('/complaints', require('./grievance'));
router.use('/live-classes', require('./liveClasses'));
router.use('/academics', require('../modules/academicsRoutes'));
router.use('/notices', require('../modules/noticesRoutes'));
router.use('/communications', require('../modules/communicationsRoutes'));
router.use('/notifications', require('./notifications'));
router.use('/config', require('./config'));
router.use('/health', require('./health'));
router.use('/upload', require('./upload'));
router.use('/reports', require('./reports'));
router.use('/exam-generator', require('./examGenerator'));
router.use('/subscriptions', require('./subscription'));
router.use('/notes', require('../modules/notesRoutes'));
router.use('/career', require('../modules/careerRoutes'));
router.use('/mentorship', require('../modules/mentorshipRoutes'));
router.use('/campus', require('../modules/campusRoutes'));
router.use('/energy', require('../modules/energyRoutes'));
router.use('/assessments', require('../modules/assessmentRoutes'));
router.use('/placement-drives', require('../modules/placementDriveRoutes'));
router.use('/intelligence', require('../modules/intelligenceRoutes'));
router.use('/placements', require('./placement'));
router.use('/placement', require('./placement'));
router.use('/library', require('./library'));
router.use('/books', require('./library'));
router.use('/grievances', require('./grievance'));
router.use('/notification-preferences', require('./notificationPreferences'));
router.use('/visitors', require('./visitor'));
router.use('/events', require('./event'));
router.use('/feedback', require('./feedback'));
router.use('/inventory', require('./inventory'));
router.use('/alumni', require('./alumni'));
router.use('/face', require('./face'));

module.exports = router;
